binbase-apps/plugins/grails-binbase-web-gui/grails-app/controllers/binbase/web/gui/ContentStatisticsController.groovy
package binbase.web.gui

import binbase.web.core.BBBin
import binbase.web.core.BBExperimentSample
import binbase.web.core.BBSpectra
import binbase.web.core.BBExperimentClass
import binbase.web.core.BBExperiment
import binbase.web.core.BBOrgan
import binbase.web.core.BBSpecies
import binbase.web.core.BBKingdom
import core.SpeciesGraphService
import grails.converters.JSON
import core.StatisticsService
import binbase.web.core.BBStatisticSnapshot

/**
 * provides some simple real time statistics
 */
class ContentStatisticsController {

    StatisticsService statisticsService

    def showStatistics = {


    }

    /**
     * shows statistics over time
     */
    def showTimeBasedStatistics = {
        [object:params.object]
    }

    /**
     * simple function to render the count of objects quickly
     */
    def ajaxRenderCountByType = {
        def value = BBStatisticSnapshot.findByObjectName(params.object,
                [
                        max: 1,
                        offset: 0,
                        sort: "createdAt",
                        order: "desc"
                ]
        )?.objectCount

        render value
    }

}

binbase-apps/plugins/grails-binbase-web-gui/grails-app/views/shared/_relatedContent.gsp
<!-- contains links to related content -->

binbase-apps/plugins/grails-binbase-web-gui/grails-app/views/shared/_sidebar.gsp
<!-- the sidebar for this application -->

<div class="sidebar">
    <div class="gadget">
        <h2 class="star"><span>Options</span></h2>

        <div class="clr"></div>
        <ul class="sb_menu">
            <li><g:link controller="BBBin">Bins</g:link></li>
            <li><g:link controller="BBExperiment">Experiments</g:link></li>
            <li><g:link controller="BBSpecies">Species</g:link></li>
            <li><g:link controller="BBOrgan">Organs</g:link></li>
            <li><g:link controller="contentStatistics" action="showStatistics">Statistics</g:link></li>
            <li><g:link controller="BBDownload" action="list">Downloads</g:link></li>

        </ul>
    </div>

    <div class="gadget">
        <h2 class="star"><span>Related Content</span></h2>

        <div class="clr"></div>
        <ul class="sb_menu">
            <g:render template="/shared/relatedContent"/>
        </ul>
    </div>
</div>