binbase-apps/apps/minix/grails-app/domain/minix/StudieDesign.groovy
package minix

import minix.step.Step

/**
 * a studie design object and basis for any studie
 */
class StudieDesign implements Comparable {

    static auditable = true

    static searchable = {
        mapping {
            boost 1.0
            spellCheck "include"
            only: ['step', 'architecture', 'speciees', 'title', 'user']
            supportUnmarshall false

        }
    }

    //has many
    static hasMany = [
            speciees: Species,
            treatmentsSpecifics: TreatmentSpecific,
            designSpeciesConnections: DesignSpeciesConnection
    ]

    //defined constraints
    static constraints = {
        title(blank: false, unique: false, minSize: 5)
        generatedStudie(nullable: true, blank: true)
        step(nullable: false)
        user(nullable: true)
    }

    /**
     * mapping
     */
    static mapping = {
        id generator: 'sequence', params: [sequence: 'MINIX_ID']
        version false

    }

    /**
     * current progress step of the design
     */
    Step step

    /**
     * related architecture
     */
    Architecture architecture

    /**
     * associated species
     */
    SortedSet<Species> speciees

    /**
     * all the species and organs
     */
    SortedSet<DesignSpeciesConnection> designSpeciesConnections

    /**
     * associated treatments with specifications
     */
    SortedSet<TreatmentSpecific> treatmentsSpecifics

    /**
     * one design can only contain one studie!
     */
    Studie generatedStudie

    /**
     * title of this studie
     */
    String title

    /**
     * number of samples
     */
    Integer numberOfSamples

    /**
     * shiro user who owns this design
     */
    ShiroUser user

    int compareTo(Object t) {
        return toString().compareTo(t.toString())
    }


    String toString() {
        return title.toString()
    }
}

binbase-apps/apps/minix/grails-app/controllers/minix/StudieDesignController.groovy
package minix

import grails.converters.deep.XML
import org.apache.shiro.SecurityUtils
import minix.step.Step
import minix.step.ThreatmentPasteDialogStep
import org.springframework.dao.DataIntegrityViolationException
import binbase.web.core.Association

/**
 * uses to design a complete experiment based on a couple of questions
 *
 */
class StudieDesignController {

    //most views can be scaffolded
    def scaffold = true

    //injected service for filename generation
    GenerateFileNameService generateFileNameService

    DesignQueryService designQueryService

    ModifyClassService modifyClassService

    def beforeInterceptor = {
        StudieDesign design = StudieDesign.get(params.designId)

        if (params.action == "ajaxRenderProgress") {
            //do nothing

        } else if (design != null && params.action != "designFileNames" && params.action != "designDone") {

            if (design.generatedStudie != null) {

                session.message = "sorry this studie design already generated a studie! This is your designed studie!"
                redirect(action: "designFileNames", params: [designId: params.designId])
            }
        }


        if (session.message) {
            flash.message = session.message
            session.message = null
        }
    }
    /**
     * render species
     */
    def ajaxRenderSpecies = {

        //reads all the species out of the params object
        Collection values = readSpecies(params)

        //render the select species field
        render(template: "selectSpecies", model: [species: values])
    }

    /**
     * deletes a treatment
     */
    def ajaxRemoveTreatment = {

        def value = params.id.toString().split("_")[1].toLong()

        StudieDesign design = StudieDesign.get(params.designId)
        TreatmentSpecific specific = TreatmentSpecific.get(value)

        //remove association from design
        design.removeFromTreatmentsSpecifics specific
        design.save(flush: true)

        //remove from parent
        if (specific.parent != null) {
            TreatmentSpecific parent = specific.parent
            parent.removeFromSubTreatmentSpecifics specific
            parent.save(flush: true)
        }

        //do the actual delete
        try {
            specific.delete(flush: true)
            flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'TreatmentSpecific.label', default: 'treatment with id: '), value])}"
        }
        catch (DataIntegrityViolationException e) {

            flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'TreatmentSpecific.label', default: 'treatment with id: '), value])}"

        }
        //render the select species field
        render(template: "designTreatments", model: [design: design])
    }
    /**
     * render the treatments
     */
    def ajaxRenderTreatments = {

        StudieDesign design = StudieDesign.get(params.designId)

        //reads all the species out of the params object
        Collection values = readTreatmentSpecifics(params)

        //assign the treatments
        assignTreatmentsToDesign(values, design)

        //render the select species field
        render(template: "selectTreatments", model: [design: design])

    }

    /**
     * read all the species from the params file
     * @param params
     * @return
     */
    protected Collection readSpecies(Map params) {
        Set values = new TreeSet()

        flash.message = ""

        Kingdom kingdom = Kingdom.findByName("None");

        if (kingdom == null) {
            kingdom = new Kingdom()
            kingdom.name = "None"
            kingdom.save(flush: true)
            log.info "generated default kingdom..."
        }
        //go over all attributes to find the one we need
        params.eachWithIndex { def value, int index ->

            //filter the attributes
            if (value.toString().startsWith("species_")) {
                String name = value.value

                if (name.length() > 0) {
                    //find the species by name
                    Species species = Species.findByName(name)

                    //if the species is null, we need to create it
                    if (species == null) {
                        species = new Species()
                        species.name = name
                        species.kingdom = kingdom

                        //validate that the species is acceptable
                        if (species.validate()) {
                            species.save(flush: true)
                        }
                    }

                    //make sure that species are unique
                    if (!values.contains(species)) {
                        values.add(species)
                    } else {
                        //duplicate species have been removed
                        flash.message = "duplicated species have been removed"
                    }
                } else {
                    flash.message = "empty fields will be ignored"

                }
            }
        }
        return values
    }

    /**
     * read all the species from the params file
     * @param params
     * @return
     */
    protected Collection readTreatmentSpecifics(Map params) {
        Collection values = new TreeSet()

        //go over all attributes to find the one we need
        params.eachWithIndex { def value, int index ->

            //filter the attributes
            if (value.toString().startsWith("treatment_name_")) {
                String name = value.value
                String fieldId = value.key.toString().split("_")[2]

                //access the id if it exist
                def treatmentSepcificValue = params."treatment_value_${fieldId}"

                //access the value if it exist
                def treatmentSepcificId = params."treatment_value_id_${fieldId}"

                if (name.length() > 0) {

                    //get our related treatment for the given name
                    Treatment treatment = defineTreatment(name)

                    //creates a specific treatment
                    TreatmentSpecific specific = createTreatmentSpecific(treatmentSepcificId, treatmentSepcificValue, treatment)

                    //call the validation
                    if (specific.validate()) {
                        specific.save(flush: true)
                    } else {
                        log.info "specific is invalid... ${specific.id} - ${specific.errors}"
                    }
                    values.add(specific)
                }
            }
        }
        return values
    }

    protected TreatmentSpecific createTreatmentSpecific(treatmentSepcificId, treatmentSepcificValue, Treatment treatment) {
        TreatmentSpecific specific = null
        //ok an id exist
        if (treatmentSepcificId.toString().size() > 0) {

            //load the treatment with the id
            specific = TreatmentSpecific.get(treatmentSepcificId.toString().toLong())
        }
        //ok we need to generate a new specific treatment
        else {
            //time to create a new treatment specific
            specific = new TreatmentSpecific()
        }

        //assign our values
        specific.setValue(treatmentSepcificValue)
        specific.treatment = treatment

        //assign to the specific
        treatment.addToSpecifics(specific)
        treatment.save(flush: true)
        return specific
    }

    protected Treatment defineTreatment(String name) {
        Treatment treatment = Treatment.findByDescription(name)

        //if the species is null, we need to create it
        if (treatment == null) {
            treatment = new Treatment()
            treatment.description = name

            //validate that the species is acceptable
            if (treatment.validate()) {
                treatment.save(flush: true)
            }
        }
        return treatment
    }

    /**
     * reads all the organs from the params for the specied species name
     * @param params
     * @return
     */
    protected Collection readOrgans(Map params, Species species) {
        Collection values = new TreeSet()

        flash.message = ""

        //go over all attributes to find the one we need
        params.eachWithIndex { def value, int index ->

            //filter the attributes
            if (value.toString().startsWith("organ_${species.id}_")) {
                String name = value.value

                if (name.length() > 0) {
                    //find the species by name
                    Organ organ = Organ.findByName(name)

                    //if the species is null, we need to create it
                    if (organ == null) {
                        organ = new Organ()
                        organ.name = name

                        //validate that the species is acceptable
                        if (organ.validate()) {

                            organ.addToSpeciees(species)
                            species.addToOrgans(organ)
                            organ.save(flush: true)
                            species.save(flush: true)
                        }
                    } else {
                        //make sure the species organ relation ship is defined
                        if (organ.speciees.contains(species) == false) {
                            organ.addToSpeciees(species)
                            species.addToOrgans(organ)
                            organ.save(flush: true)
                            species.save(flush: true)
                        }
                    }

                    //make sure that species are unique
                    if (!values.contains(organ)) {
                        values.add(organ)
                    } else {
                        //duplicate species have been removed

binbase-apps/apps/minix/grails-app/views/studieDesign/_defineFileNames.gsp
<%
    assert design != null, "you need to provide a design object!"
%>
<g:setProvider library="jquery"/>


<div class="design">
    <div class="left">
        <g:render template="stepView" model="[design:design]"/>
    </div>
    <g:form name="defineFileNames" action="designDone">

        <div class="left-center-column">
            <div class="step-dialog">

                <div class="header">
                    step 6 - class modification
                </div>

                <div class="description">
                    modify these classes to fit your exact experimental design. Once done, please press save to finalize your design.
                </div>

                <g:render template="/shared/validation_error" model="[errorBean:design]"/>

                <div class="topSpacer"></div>



                <g:hiddenField name="designId" id="designId" value="${design?.id}"/>
                <g:hiddenField name="studieId" id="studieId" value="${design.generatedStudie.id}"/>

                <g:each var="clazz" in="${design.generatedStudie.classes}">
                    <g:render template="/experimentClass/displayClass" model="[clazz:clazz]"/>
                </g:each>

            </div>

            <div class="button-margin-top">
                <g:submitButton class="next" name="designDone" value="save and display generated studie"/>
            </div>
        </div>
    </g:form>

</div>

binbase-apps/apps/minix/grails-app/views/studieDesign/_designDone.gsp
<link rel="stylesheet" href="${resource(dir: 'css', file: 'studieDesign.css')}"/>

<g:setProvider library="jquery"/>

<script type="text/javascript">
    $(document).ready(function () {

        function countdown() {
            if (typeof countdown.counter == 'undefined') {
                countdown.counter = 5; // initial count
            }
            if (countdown.counter > 0) {
                document.getElementById('count').innerHTML = countdown.counter--;
                setTimeout(countdown, 1000);
            }
            else {
                location.href = "${g.createLink(controller: "studie",action: "show",id:design.generatedStudie.id)}";
            }
        }

        countdown();

    });
</script>

<div class="design">
    <div class="left">
        <g:render template="stepView" model="[design: design]"/>
    </div>

    <div class="left-center-column">

        <div>

            congratulations, your study design is done and you will
            be forwarded in <span id="count"></span> seconds to your study for further actions.

            <p>
                If this page doesn't change, please press
                <g:link controller="studie" action="show"
                        id="${design.generatedStudie.id}">this link</g:link> to continue.

            </p>
        </div>
    </div>
</div>

binbase-apps/apps/minix/grails-app/views/studieDesign/_designSamples.gsp
<g:setProvider library="jquery"/>
<link rel="stylesheet" href="${resource(dir: 'css', file: 'studieDesign.css')}"/>

<div class="design">
    <div class="left">
        <g:render template="stepView" model="[design:design]"/>
    </div>

    <div class="left-center-column">
        <g:form name="designSamples">
            <div class="step-dialog">

                <div class="header">
                    step 4 - class generation properties
                </div>

                <div class="description">
                    at this step you define general class properties.
                </div>

                <g:render template="/shared/validation_error" model="[errorBean:design]"/>

                <div class="textDescription">
                    please select how many samples each class should have
                </div>


                <div class="${hasErrors(bean: design, field: 'numberOfSamples', 'errors')}">
                    <div class="textField">
                        <g:textField name="numberOfSamples" value="${design?.numberOfSamples}"/>
                    </div>
                </div>

                <!-- store the hidden id-->
                <g:hiddenField name="designId" id="designId" value="${design?.id}"/>
            </div>

            <div class="button-margin-top">
                <g:submitToRemote class="next" action="ajaxSaveSamples" name="ajaxSaveSamples" id="ajaxSaveSamples"
                                  value="continue to step 5" update="next"/>
            </div>
        </g:form>

    </div>
</div>

binbase-apps/apps/minix/grails-app/views/studieDesign/_designSubtreatment.gsp
<g:setProvider library="jquery"/>

<%
  assert treatmentSpecific != null, "you need to provide a variable with the name 'treatmentSpecific'"
%>


<g:javascript>
  $(document).ready(function() {

    $(function() {

      $("#sub_treatment_0")
      .autocomplete({
              source: '${g.createLink(action: "findTreatment", controller: "autoCompletion")}', dataType:"json"
              }
      );
    })
  });
</g:javascript>

<g:javascript>
  $(document).ready(function() {

    $(function() {

      $("#sub_treatment_value_0")
      .autocomplete({
              source: '${g.createLink(action: "findTreatmentValue", controller: "autoCompletion")}', dataType:"json"
              }
      );
    })
  });
</g:javascript>


<div class="defineSubTreatment">
  <div class="header">
    step 3.1 - please define a sub treatment for ${treatmentSpecific.toParentString()}
  </div>
  <div class="description">
    please define the subtreatment using the fields below and press 'save' to finalize this change.
  </div>

  <div class="topSpacer">

  </div>
  <table>
    <thead>
    <tr>
      <th>name</th>
      <th>specific</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><g:textField name="sub_treatment_name_0" id="sub_treatment_0"/>
      </td>
      <td><g:textField name="sub_treatment_value_0" id="sub_treatment_value_0"/>
      </td>
      <td>

        <g:hiddenField name="sub_treatment_parent_id_0" id="sub_treatment_parent_id_0" value="${treatmentSpecific.id}"/>

        <div class="buttons">
          <g:submitToRemote class="add" action="ajaxSaveSubtreatment" name="saveSubTreatment" id="saveSubTreatment" value="save" update="selectTreatmentDiv"/>
        </div>

      </td>
    </tr>
    </tbody>
  </table>
</div>

binbase-apps/apps/minix/grails-app/views/studieDesign/_stepView.gsp
<%@ page import="minix.step.Step" %>
<!-- used to display the step view -->
<g:setProvider library="jquery"/>

<%
    def step = null

    if (design != null) {
        step = design.step
    }
    else {
        step = Step.DEFINE_SPECIES
    }

    def locked = step > Step.GENERATE_CLASS
%>

<div class="header">

    Design Progress Monitor

</div>

<div class="monitor">
    <ul class="monitor">
        <g:each var="myStep" in="${Step.listEnums()}">

            <g:if test="${myStep.equals(step)}">
                <li class="current">
                    <g:if test="${design == null}">
                        ${myStep.message}
                    </g:if>
                    <g:else>
                        <g:link action="${myStep.method}" params="[designId:design.id]">${myStep.message}</g:link>
                    </g:else>
                </li>
            </g:if>
            <g:else>
                <g:if test="${myStep < step}">
                    <g:if test="${locked }">
                        <li class="previous_locked">
                            ${myStep.message}
                        </li>
                    </g:if>
                    <g:else>
                        <li class="previous">
                            <g:link action="${myStep.method}" params="[designId:design.id]">${myStep.message}</g:link>
                        </li>
                    </g:else>
                </g:if>
                <g:else>
                    <li class="next">${myStep.message}</li>
                </g:else>
            </g:else>
        </g:each>
    </ul>
</div>


<div class="header">

    Information

</div>

<g:if test="${design != null}">
    <g:if test="${design.user != null}">

        <div class="left_information_box">
            Owning user: ${design.user}
        </div>
    </g:if>
</g:if>
<g:else>
    <div class="left_information_box">
        no information's are available at this point in time
    </div>

</g:else>
<g:if test="${locked}">

    <div class="left_information_box">
        at this point your study is generated and has samples assigned, so you cannot go back to a previous step! You are only able to adjust class properties and file properties
    </div>
</g:if>

<div class="topSpacer"></div>
<div class="header">
    Options
</div>

<div class="monitor">
    <ul class="monitor">
        <g:if test="${design != null && design.generatedStudie == null}">
            <li><g:link class="remove" action="delete" controller="studieDesign" id="${design.id}">delete design</g:link></li>
        </g:if>
    </ul>
    <ul class="monitor">
        <g:if test="${design != null}">
            <li><g:link class="copy" action="duplicateDesign" controller="studieDesign" id="${design.id}">duplicate design</g:link></li>
        </g:if>
    </ul>


</div>

binbase-apps/apps/minix/grails-app/views/studieDesign/edit.gsp
<%@ page import="minix.StudieDesign" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'studieDesign.label', default: 'StudieDesign')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
            <span class="menuButton"><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${studieDesignInstance}">
            <div class="errors">
                <g:renderErrors bean="${studieDesignInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <g:hiddenField name="id" value="${studieDesignInstance?.id}" />
                <g:hiddenField name="version" value="${studieDesignInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="title"><g:message code="studieDesign.title.label" default="Title" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'title', 'errors')}">
                                    <g:textField name="title" value="${studieDesignInstance?.title}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="generatedStudie"><g:message code="studieDesign.generatedStudie.label" default="Generated Studie" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'generatedStudie', 'errors')}">
                                    <g:select name="generatedStudie.id" from="${minix.Studie.list()}" optionKey="id" value="${studieDesignInstance?.generatedStudie?.id}" noSelection="['null': '']" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="step"><g:message code="studieDesign.step.label" default="Step" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'step', 'errors')}">
                                    <g:select name="step" from="${minix.step.Step?.values()}" value="${studieDesignInstance?.step}"  />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="architecture"><g:message code="studieDesign.architecture.label" default="Architecture" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'architecture', 'errors')}">
                                    <g:select name="architecture.id" from="${minix.Architecture.list()}" optionKey="id" value="${studieDesignInstance?.architecture?.id}"  />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="designSpeciesConnections"><g:message code="studieDesign.designSpeciesConnections.label" default="Design Species Connections" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'designSpeciesConnections', 'errors')}">
                                    
<ul>
<g:each in="${studieDesignInstance?.designSpeciesConnections?}" var="d">
    <li><g:link controller="designSpeciesConnection" action="show" id="${d.id}">${d?.encodeAsHTML()}</g:link></li>
</g:each>
</ul>
<g:link controller="designSpeciesConnection" action="create" params="['studieDesign.id': studieDesignInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'designSpeciesConnection.label', default: 'DesignSpeciesConnection')])}</g:link>

                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="numberOfSamples"><g:message code="studieDesign.numberOfSamples.label" default="Number Of Samples" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'numberOfSamples', 'errors')}">
                                    <g:textField name="numberOfSamples" value="${fieldValue(bean: studieDesignInstance, field: 'numberOfSamples')}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="speciees"><g:message code="studieDesign.speciees.label" default="Speciees" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'speciees', 'errors')}">
                                    <g:select name="speciees" from="${minix.Species.list()}" multiple="yes" optionKey="id" size="5" value="${studieDesignInstance?.speciees}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="treatmentsSpecifics"><g:message code="studieDesign.treatmentsSpecifics.label" default="Treatments Specifics" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'treatmentsSpecifics', 'errors')}">
                                    <g:select name="treatmentsSpecifics" from="${minix.TreatmentSpecific.list()}" multiple="yes" optionKey="id" size="5" value="${studieDesignInstance?.treatmentsSpecifics}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="user"><g:message code="studieDesign.user.label" default="User" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: studieDesignInstance, field: 'user', 'errors')}">
                                    <g:select name="user.id" from="${minix.ShiroUser.list()}" optionKey="id" value="${studieDesignInstance?.user?.id}"  />
                                </td>
                            </tr>
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" /></span>
                    <span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

binbase-apps/apps/minix/grails-app/views/studieDesign/list.gsp
<%@ page import="minix.ShiroUser; minix.StudieDesign" %>


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="main"/>
    <title>StudieDesign List</title>
</head>
<body>
<g:render template="/shared/navigation"/>

<div class="body">

    <div class="design">

        <div class="left">
            <div class="header">

                Information

            </div>

            <div class="left_information_box">
                <p><g:message code="description.design"/></p>
            </div>

        </div>
        <div class="left-center-column">
            <div class="header">StudieDesign List</div>
            <g:if test="${flash.message}">
                <div class="message">${flash.message}</div>
            </g:if>
            <div class="element">
                <ul class="none-horizontal">
                    <!-- here we are registering our gctofs systems -->
                    <li><g:link class="add" controller="studieDesign" action="create"><g:message code="new.studie.design"/></g:link></li>
                </ul>
            </div>

            <div class="element">
<g:render template="table/designTable" model="[studieDesignCount:studieDesignCount,studieDesignInstanceList:studieDesignInstanceList]"/>


<g:if test="${ShiroUser.hasAdminRights()}">
    <div class="element">
        <ul class="none-horizontal">
            <!-- here we are registering our gctofs systems -->
            <li>
                <g:link class="list" controller="studieDesign" action="listAll">list all accesible designs</g:link>
            </li>
        </ul>
    </div>
</g:if>
            </div>
        </div>

    </div>
</div>
</body>
</html>